<?php
/**
 * @file
 * Returns the HTML for the footer region.
 *
 * Complete documentation for this file is available online.
 * @see https://drupal.org/node/1728140
 */

global $base_url;
?>
<footer id="footer" class="<?php print $classes; ?>">

<!--   <div >
  	<img class="logo" alt="GCLS logo" src="sites/all/themes/gcls/images/Logo2016.png">
  </div> -->
    

<div class="fhours">
  <div>
    Hughes Main Hours:<br>
    Mon-Fri: 9am-9pm<br>
    Sat: 9am-6pm<br>
    Sun: 2pm-6pm
  </div>
  <div>
    Branch Hours:<br>
    Mon-Thurs: 9am-9pm<br>
    Fri-Sun: 9am-6pm
    <br> 
  </div>
  <br>
  <div class="address">
    25 Heritage Green |
    Greenville, SC 29601 | 
    (864) 242-5000
    <br>
    &copy; 2016 Greenville County Library System  
  </div>
</div>

<div class="footerlinks">
  <div>
    <div>
      <a href="#">About Us</a><br>
      <a href="http://www.greenvillelibrary.org/index.php/about/contact-us">Contact Us</a><br>
      <a href="http://libanswers.greenvillelibrary.org/">Help</a><br> 
    </div>
    <div>
      <a href="http://www.greenvillelibrary.org/index.php/about/locations-hours">Locations/Hours</a><br>
      <a href="#">Job Openings</a><br>
      <a href="#">Library News</a><br>
    </div>
  </div>
  <br>
  <div class="icons">
    <a href="http://www.facebook.com/greenvillelibrary" target="_blank"><img alt="Facebook" src="<?php print $base_url; ?>/sites/all/themes/gcls/images/face.png"></a>
    <a href="http://twitter.com/GCLSLibrary" target="_blank"><img alt="Twitter" src="<?php print $base_url; ?>/sites/all/themes/gcls/images/twit.png"></a>
    <a href="http://www.youtube.com/user/GreenvilleLibrary" target="_blank"><img alt="YouTube" src="<?php print $base_url; ?>/sites/all/themes/gcls/images/yout.png"></a>
    <a href="http://pinterest.com/gcls/" target="_blank"><img alt="Pinterest" src="<?php print $base_url; ?>/sites/all/themes/gcls/images/pin.png"></a>
    <a href="http://instagram.com/greenvillelibrary" target="_blank"><img alt="Instagram" src="<?php print $base_url; ?>/sites/all/themes/gcls/images/insta.png"></a>
  </div>
</div>

</footer>